# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 15:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import hfl.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('office_phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message=b"Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex=b'^\\+?1?\\d{9,15}$')])),
                ('mobile_phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message=b"Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex=b'^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254)),
                ('avatar', models.ImageField(upload_to=b'')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=80)),
                ('year_in_school', models.CharField(choices=[(b'Commercial', b'Commercial'), (b'Residential', b'Residential'), (b'Land', b'Land')], default=b'Commercial', max_length=20)),
                ('county', models.CharField(max_length=60)),
                ('zip', models.CharField(max_length=20)),
                ('zoning', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[(b'Available', b'Available'), (b'Under Contract', b'Under Contract'), (b'Sold', b'Sold')], default=b'Available', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('property_taxes', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'static/images/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='ListingVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=b'static/videos/%Y/%m/%d', validators=[hfl.validators.validate_video_extension])),
            ],
        ),
        migrations.CreateModel(
            name='CommercialListing',
            fields=[
                ('listing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hfl.Listing')),
                ('average_utilities', models.DecimalField(decimal_places=2, max_digits=20)),
                ('truck_bays', models.DecimalField(decimal_places=2, max_digits=20)),
                ('slab_depth', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ceiling_height', models.IntegerField()),
                ('air_conditioned_space', models.IntegerField()),
            ],
            bases=('hfl.listing',),
        ),
        migrations.CreateModel(
            name='LandListing',
            fields=[
                ('listing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hfl.Listing')),
                ('acreage', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            bases=('hfl.listing',),
        ),
        migrations.CreateModel(
            name='ResidentialListing',
            fields=[
                ('listing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hfl.Listing')),
                ('amenities', models.TextField()),
                ('heating', models.CharField(max_length=100)),
                ('cooling', models.CharField(max_length=100)),
                ('utilities', models.CharField(max_length=100)),
                ('rent_potential', models.DecimalField(decimal_places=2, max_digits=20)),
                ('hoa', models.BooleanField()),
                ('hoa_dues', models.DecimalField(decimal_places=2, max_digits=20)),
                ('extras', models.TextField()),
                ('garage', models.BooleanField()),
                ('square_feet', models.DecimalField(decimal_places=2, max_digits=20)),
                ('appliances', models.CharField(max_length=100)),
            ],
            bases=('hfl.listing',),
        ),
        migrations.AddField(
            model_name='listingvideo',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hfl.Listing'),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hfl.Listing'),
        ),
        migrations.AddField(
            model_name='listing',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hfl.Agent'),
        ),
    ]
