# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hfl', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='year_in_school',
            new_name='listing_type',
        ),
    ]
