# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hfl', '0002_auto_20171218_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingimage',
            options={'verbose_name': 'Picture', 'verbose_name_plural': 'Pictures'},
        ),
        migrations.AddField(
            model_name='listingimage',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
