# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hfl', '0003_auto_20171218_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commerciallisting',
            name='air_conditioned_space',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='commerciallisting',
            name='average_utilities',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='commerciallisting',
            name='ceiling_height',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='commerciallisting',
            name='slab_depth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='commerciallisting',
            name='truck_bays',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='landlisting',
            name='acreage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_taxes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(blank=True, choices=[(b'Available', b'Available'), (b'Under Contract', b'Under Contract'), (b'Sold', b'Sold')], default=b'Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='zoning',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='residentiallisting',
            name='amenities',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='residentiallisting',
            name='appliances',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='residentiallisting',
            name='cooling',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='residentiallisting',
            name='extras',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='residentiallisting',
            name='heating',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='residentiallisting',
            name='hoa_dues',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='residentiallisting',
            name='rent_potential',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='residentiallisting',
            name='square_feet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='residentiallisting',
            name='utilities',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
